### ISSUE TITLE
嘉宾录入错误和调整

### ISSUE THREAD

**Issue by CynthiaXin1** [PyConChina/PyConChina2019#36]
1. 上海场嘉宾 崔衡 换到 北京场 费良宏 后面
2. 上海场嘉宾： 黄少瑄 ， 刘玉龙 应该调整到北京场最后（因为是快速演讲嘉宾）

**Comment by CynthiaXin1** [comment]
3. 深圳场，最前面新增嘉宾： GIAMPAOLO RODOLA （上海场已有资料）

**Comment by CynthiaXin1** [comment]
4.成都场新增嘉宾：藤井美娜 （上海场已有资料，在姓名后面增加（日本）这样的备注字眼）

**Comment by greyli** [comment]
另外还有 Giampaolo 的主题名称不对：
![image](https://user-images.githubusercontent.com/12967000/62816416-a5d20a00-bb59-11e9-888e-c7478b1111a6.png)
李辉的演讲议题（同时报名了主题和闪电演讲各一个）显示的是闪电演讲，而不是主题演讲。

**Comment by greyli** [comment]
Fixed in https://github.com/PyConChina/PyConChina2019/commit/afd4659e60f6b9bd522e51018898c78bcc80fb08.
